# -*- coding: utf-8 -*-
"""VilleStats.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mXMHuezLEQfKb3vvQWEndwsJzreO9VyD
"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

# Données historiques
years = [1800, 1825, 1852, 1871, 1901, 1921, 1931, 1951, 1961, 1971,
         1981, 1991, 2001, 2006, 2011, 2016, 2021, 2023, 2025]
population = [9000, 23000, 58000, 107225, 267730, 618506, 818577, 1021520,
              1191062, 1214352, 1018609, 1017666, 1812723, 3635556, 3824221,
              4098927, 4291732, 4308000, 4377000]

# Création du graphique
plt.figure(figsize=(14, 8))
plt.style.use('seaborn-v0_8')
plt.grid(True, which="both", ls="-", alpha=0.2)

# Tracé en échelle logarithmique
plt.semilogy(years, population, marker='o', color='#1f77b4',
             linewidth=2.5, markersize=8, markerfacecolor='white', markeredgewidth=2)

# Personnalisation
plt.title('Évolution démographique de Montréal (1800–2025)\nÉchelle logarithmique',
          fontsize=16, pad=20, fontweight='bold')
plt.xlabel('Année', fontsize=12)
plt.ylabel('Population (échelle log)', fontsize=12)
plt.xticks(np.arange(1800, 2030, 20), rotation=45)
plt.yticks([1e3, 1e4, 1e5, 1e6, 1e7], ['1k', '10k', '100k', '1M', '10M'])

# Annotations
annotations = [
    (1825, 23000, "Début urbanisation\n(1800–1850)", 'green', (1810, 5000)),
    (1901, 267730, "Industrialisation\n(1850–1930)", 'green', (1870, 1e5)),
    (1971, 1214352, "Pic historique\n(1971: 1,2M hab.)", 'black', (1950, 2e6)),
    (1981, 1018609, "Exode vers banlieues\n(1970–1990)", 'red', (1975, 5e5)),
    (2016, 4098927, "Croissance métropolitaine\n(2000–2025)", 'blue', (2005, 2e6))
]

for x, y, text, color, xytext in annotations:
    plt.annotate(text,
                 xy=(x, y), xytext=xytext,
                 arrowprops=dict(facecolor=color, shrink=0.05, width=2),
                 bbox=dict(boxstyle="round", alpha=0.1, color=color),
                 fontsize=10)

# Valeurs clés
for year, pop in zip(years, population):
    if year in [1852, 1901, 1951, 1971, 2001, 2025]:
        plt.text(year, pop * 1.1, f"{pop:,}".replace(",", " "),
                 ha='center', fontsize=9, fontweight='bold')

plt.tight_layout()
plt.savefig('montreal_population.png', dpi=300, bbox_inches='tight')
plt.show()

import matplotlib.pyplot as plt
import numpy as np

# ============================================
# PARAMÈTRES - Boston
# ============================================
CITY_NAME = "Boston"
CITY_COLOR = '#2ecc71'

years = [1810, 1820, 1830, 1840, 1850, 1860, 1870, 1880, 1890, 1900,
         1910, 1920, 1930, 1940, 1950, 1960, 1970, 1980, 1990, 2000]
population = [33787, 43298, 61392, 93383, 136881, 177840, 250526, 362839,
              448477, 560892, 670585, 748060, 781188, 770816, 801444,
              697197, 641071, 562994, 574283, 589141]

annotations = [
    (1850, 136881,  "Vague immigration irlandaise",  'green',  (1820, 50000)),
    (1900, 560892,  "Industrialisation",              'green',  (1870, 200000)),
    (1950, 801444,  "Pic historique: 801k",           'black',  (1920, 1200000)),
    (1970, 641071,  "Exode banlieues",                'red',    (1955, 350000)),
    (2000, 589141,  "Légère reprise",                 'blue',   (1985, 150000)),
]

key_years = [1850, 1900, 1930, 1950, 1970, 2000]
# ============================================

fig, ax = plt.subplots(figsize=(14, 8))
plt.style.use('seaborn-v0_8')

ax.semilogy(years, population, marker='o', color=CITY_COLOR,
            linewidth=2.5, markersize=8, markerfacecolor='white', markeredgewidth=2)

ax.grid(True, which="both", ls="-", alpha=0.2)
ax.set_title(f'Évolution démographique de {CITY_NAME}\nÉchelle logarithmique',
             fontsize=16, pad=20, fontweight='bold')
ax.set_xlabel('Année', fontsize=12)
ax.set_ylabel('Population (échelle log)', fontsize=12)
ax.set_xticks(np.arange(min(years), max(years)+10, 10))
plt.xticks(rotation=45)
ax.set_yticks([1e4, 1e5, 1e6])
ax.set_yticklabels(['10k', '100k', '1M'])

for x, y, text, color, xytext in annotations:
    ax.annotate(text, xy=(x, y), xytext=xytext,
                arrowprops=dict(facecolor=color, shrink=0.05, width=2),
                bbox=dict(boxstyle="round", alpha=0.1, color=color),
                fontsize=10)

for year, pop in zip(years, population):
    if year in key_years:
        ax.text(year, pop * 1.15, f"{pop:,}".replace(",", " "),
                ha='center', fontsize=9, fontweight='bold')

plt.tight_layout()
plt.savefig(f'{CITY_NAME.lower()}_population.png', dpi=300, bbox_inches='tight')
plt.show()

import matplotlib.pyplot as plt
import numpy as np

# ============================================
# PARAMÈTRES - St. Louis, Missouri
# ============================================
CITY_NAME = "St. Louis, Missouri"
CITY_COLOR = '#e74c3c'

years = [1810, 1820, 1830, 1840, 1850, 1860, 1870, 1880, 1890, 1900,
         1910, 1920, 1930, 1940, 1950, 1960, 1970, 1980, 1990, 2000]
population = [1400, 4598, 5852, 16469, 77860, 160773, 310864, 350518,
              451770, 575238, 687029, 772897, 821960, 816048, 856796,
              750026, 622236, 453085, 396685, 348189]

annotations = [
    (1850, 77860,   "Porte vers l'Ouest",            'green',  (1820, 30000)),
    (1870, 310864,  "Boom ferroviaire",               'green',  (1845, 100000)),
    (1950, 856796,  "Pic historique: 857k",           'black',  (1925, 1500000)),
    (1960, 750026,  "Début exode urbain",             'red',    (1940, 300000)),
    (2000, 348189,  "Déclin -59% en 50 ans",          'red',    (1980, 100000)),
]

key_years = [1850, 1870, 1900, 1930, 1950, 1970, 2000]
# ============================================

fig, ax = plt.subplots(figsize=(14, 8))
plt.style.use('seaborn-v0_8')

ax.semilogy(years, population, marker='o', color=CITY_COLOR,
            linewidth=2.5, markersize=8, markerfacecolor='white', markeredgewidth=2)

ax.grid(True, which="both", ls="-", alpha=0.2)
ax.set_title(f'Évolution démographique de {CITY_NAME}\nÉchelle logarithmique',
             fontsize=16, pad=20, fontweight='bold')
ax.set_xlabel('Année', fontsize=12)
ax.set_ylabel('Population (échelle log)', fontsize=12)
ax.set_xticks(np.arange(min(years), max(years)+10, 10))
plt.xticks(rotation=45)
ax.set_yticks([1e3, 1e4, 1e5, 1e6])
ax.set_yticklabels(['1k', '10k', '100k', '1M'])

for x, y, text, color, xytext in annotations:
    ax.annotate(text, xy=(x, y), xytext=xytext,
                arrowprops=dict(facecolor=color, shrink=0.05, width=2),
                bbox=dict(boxstyle="round", alpha=0.1, color=color),
                fontsize=10)

for year, pop in zip(years, population):
    if year in key_years:
        ax.text(year, pop * 1.15, f"{pop:,}".replace(",", " "),
                ha='center', fontsize=9, fontweight='bold')

plt.tight_layout()
plt.savefig(f'stlouis_population.png', dpi=300, bbox_inches='tight')
plt.show()

import matplotlib.pyplot as plt
import numpy as np

# ============================================
# PARAMÈTRES - Sorel, Québec
# ============================================
CITY_NAME = "Sorel, Québec"
CITY_COLOR = '#3498db'

years = [1831, 1851, 1861, 1871, 1881, 1891, 1901, 1911, 1921, 1931,
         1941, 1951, 1961, 1971, 1981, 1991, 2001, 2011, 2021]
population = [1500, 3200, 4100, 4800, 5900, 6800, 7179, 8516, 10243, 11819,
              14961, 17147, 19347, 19347, 20347, 18748, 18127, 17463, 16810]

annotations = [
    (1851, 3200,   "Essor portuaire",               'blue',   (1831, 6000)),
    (1941, 14961,  "Boom chantiers navals WWII",     'green',  (1911, 20000)),
    (1981, 20347,  "Pic historique: 20 347",         'black',  (1955, 35000)),
    (1991, 18748,  "Fermeture chantiers navals",     'red',    (1971, 10000)),
    (2001, 18127,  "Fusion → Sorel-Tracy",           'purple', (1985, 8000)),
]

key_years = [1851, 1901, 1941, 1951, 1981, 2001, 2021]
# ============================================

fig, ax = plt.subplots(figsize=(14, 8))
plt.style.use('seaborn-v0_8')

ax.semilogy(years, population, marker='o', color=CITY_COLOR,
            linewidth=2.5, markersize=8, markerfacecolor='white', markeredgewidth=2)

ax.grid(True, which="both", ls="-", alpha=0.2)
ax.set_title(f'Évolution démographique de {CITY_NAME}\nÉchelle logarithmique',
             fontsize=16, pad=20, fontweight='bold')
ax.set_xlabel('Année', fontsize=12)
ax.set_ylabel('Population (échelle log)', fontsize=12)
ax.set_xticks(years)
plt.xticks(rotation=45)
ax.set_yticks([1e3, 1e4, 1e5])
ax.set_yticklabels(['1k', '10k', '100k'])

for x, y, text, color, xytext in annotations:
    ax.annotate(text, xy=(x, y), xytext=xytext,
                arrowprops=dict(facecolor=color, shrink=0.05, width=2),
                bbox=dict(boxstyle="round", alpha=0.1, color=color),
                fontsize=10)

for year, pop in zip(years, population):
    if year in key_years:
        ax.text(year, pop * 1.15, f"{pop:,}".replace(",", " "),
                ha='center', fontsize=9, fontweight='bold')

plt.tight_layout()
plt.savefig('sorel_population.png', dpi=300, bbox_inches='tight')
plt.show()

import matplotlib.pyplot as plt
import numpy as np

# ============================================
# PARAMÈTRES - New Orleans, Louisiana
# ============================================
CITY_NAME = "New Orleans, Louisiana"
CITY_COLOR = '#8e44ad'

years = [1810, 1820, 1830, 1840, 1850, 1860, 1870, 1880, 1890, 1900,
         1910, 1920, 1930, 1940, 1950, 1960, 1970, 1980, 1990, 2000,
         2005, 2010, 2020]
population = [17242, 27176, 46082, 102193, 116375, 168675, 191418, 216090,
              242039, 287104, 339075, 387219, 458762, 494537, 570445, 627525,
              593471, 557515, 496938, 484674, 127000, 343829, 383997]

annotations = [
    (1840, 102193,  "Boom coton/commerce",           'green',  (1820, 200000)),
    (1960, 627525,  "Pic historique: 627k",          'black',  (1935, 900000)),
    (1970, 593471,  "Début déclin urbain",           'red',    (1945, 350000)),
    (2005, 127000,  "🌊 Katrina -73%!",              'red',    (1990, 80000)),
    (2020, 383997,  "Reconstruction partielle",      'blue',   (2008, 200000)),
]

key_years = [1840, 1900, 1940, 1960, 1980, 2000, 2005, 2010, 2020]
# ============================================

fig, ax = plt.subplots(figsize=(14, 8))
plt.style.use('seaborn-v0_8')

ax.semilogy(years, population, marker='o', color=CITY_COLOR,
            linewidth=2.5, markersize=8, markerfacecolor='white', markeredgewidth=2)

# Zone Katrina
ax.axvspan(2003, 2007, alpha=0.15, color='red', label='Ouragan Katrina')

ax.grid(True, which="both", ls="-", alpha=0.2)
ax.set_title(f'Évolution démographique de {CITY_NAME}\nÉchelle logarithmique',
             fontsize=16, pad=20, fontweight='bold')
ax.set_xlabel('Année', fontsize=12)
ax.set_ylabel('Population (échelle log)', fontsize=12)
ax.set_xticks(years)
plt.xticks(rotation=45)
ax.set_yticks([1e4, 1e5, 1e6])
ax.set_yticklabels(['10k', '100k', '1M'])
ax.legend(fontsize=11)

for x, y, text, color, xytext in annotations:
    ax.annotate(text, xy=(x, y), xytext=xytext,
                arrowprops=dict(facecolor=color, shrink=0.05, width=2),
                bbox=dict(boxstyle="round", alpha=0.1, color=color),
                fontsize=10)

for year, pop in zip(years, population):
    if year in key_years:
        ax.text(year, pop * 1.15, f"{pop:,}".replace(",", " "),
                ha='center', fontsize=9, fontweight='bold')

plt.tight_layout()
plt.savefig('neworleans_population.png', dpi=300, bbox_inches='tight')
plt.show()

import matplotlib.pyplot as plt
import numpy as np

# ============================================
# PARAMÈTRES - Nashville, Tennessee
# ============================================
CITY_NAME = "Nashville, Tennessee"
CITY_COLOR = '#e67e22'

years = [1800, 1810, 1820, 1830, 1840, 1850, 1860, 1870, 1880, 1890,
         1900, 1910, 1920, 1930, 1940, 1950, 1960, 1970, 1980, 1990,
         2000, 2010, 2020]
population = [345, 1100, 3462, 5566, 6929, 10165, 16988, 25865, 43350, 76168,
              80865, 110364, 118342, 153866, 167402, 174307, 170874, 448003,
              477811, 510784, 569891, 626144, 689447]

annotations = [
    (1890, 76168,   "Boom ferroviaire",              'green',  (1870, 180000)),
    (1950, 174307,  "Avant fusion ville/comté",      'black',  (1925, 350000)),
    (1970, 448003,  "🚀 Fusion 1963 +162%!",         'blue',   (1945, 700000)),
    (2000, 569891,  "Sun Belt boom",                 'green',  (1982, 900000)),
    (2020, 689447,  "Croissance continue",           'green',  (2005, 300000)),
]

key_years = [1850, 1890, 1910, 1950, 1960, 1970, 2000, 2010, 2020]
# ============================================

fig, ax = plt.subplots(figsize=(14, 8))
plt.style.use('seaborn-v0_8')

ax.semilogy(years, population, marker='o', color=CITY_COLOR,
            linewidth=2.5, markersize=8, markerfacecolor='white', markeredgewidth=2)

# Zone fusion ville/comté
ax.axvspan(1961, 1965, alpha=0.15, color='blue', label='Fusion ville/comté 1963')

# Zone Sun Belt
ax.axvspan(1970, 2020, alpha=0.05, color='green', label='Ère Sun Belt')

ax.grid(True, which="both", ls="-", alpha=0.2)
ax.set_title(f'Évolution démographique de {CITY_NAME}\nÉchelle logarithmique',
             fontsize=16, pad=20, fontweight='bold')
ax.set_xlabel('Année', fontsize=12)
ax.set_ylabel('Population (échelle log)', fontsize=12)
ax.set_xticks(years)
plt.xticks(rotation=45)
ax.set_yticks([1e2, 1e3, 1e4, 1e5, 1e6])
ax.set_yticklabels(['100', '1k', '10k', '100k', '1M'])
ax.legend(fontsize=11)

for x, y, text, color, xytext in annotations:
    ax.annotate(text, xy=(x, y), xytext=xytext,
                arrowprops=dict(facecolor=color, shrink=0.05, width=2),
                bbox=dict(boxstyle="round", alpha=0.1, color=color),
                fontsize=10)

for year, pop in zip(years, population):
    if year in key_years:
        ax.text(year, pop * 1.15, f"{pop:,}".replace(",", " "),
                ha='center', fontsize=9, fontweight='bold')

plt.tight_layout()
plt.savefig('nashville_population.png', dpi=300, bbox_inches='tight')
plt.show()

import matplotlib.pyplot as plt
import numpy as np

# ============================================
# PARAMÈTRES - Cincinnati, Ohio
# ============================================
CITY_NAME = "Cincinnati, Ohio"
CITY_COLOR = '#c0392b'

years = [1800, 1810, 1820, 1830, 1840, 1850, 1860, 1870, 1880, 1890,
         1900, 1910, 1920, 1930, 1940, 1950, 1960, 1970, 1980, 1990,
         2000, 2010, 2020]
population = [750, 2540, 9642, 24831, 46338, 115436, 161044, 216239, 255139,
              296908, 325902, 363591, 401247, 451160, 455610, 503998, 502550,
              452524, 385457, 364040, 331285, 296943, 309317]

annotations = [
    (1840, 46338,   "🐷 Porkopolis",                 'brown',  (1815, 120000)),
    (1850, 115436,  "6ème ville USA!",               'green',  (1832, 350000)),
    (1900, 325902,  "Immigration allemande",         'blue',   (1878, 600000)),
    (1950, 503998,  "Pic historique: 503k",          'black',  (1925, 800000)),
    (1970, 452524,  "Début suburbanisation",         'red',    (1948, 200000)),
    (2020, 309317,  "Légère reprise +4%",            'green',  (2003, 100000)),
]

key_years = [1830, 1850, 1900, 1930, 1950, 1970, 1990, 2010, 2020]
# ============================================

fig, ax = plt.subplots(figsize=(14, 8))
plt.style.use('seaborn-v0_8')

ax.semilogy(years, population, marker='o', color=CITY_COLOR,
            linewidth=2.5, markersize=8, markerfacecolor='white', markeredgewidth=2)

# Zone croissance
ax.axvspan(1800, 1950, alpha=0.05, color='green', label='Ère croissance')
# Zone déclin
ax.axvspan(1950, 2010, alpha=0.05, color='red', label='Ère déclin urbain')

ax.grid(True, which="both", ls="-", alpha=0.2)
ax.set_title(f'Évolution démographique de {CITY_NAME}\nÉchelle logarithmique',
             fontsize=16, pad=20, fontweight='bold')
ax.set_xlabel('Année', fontsize=12)
ax.set_ylabel('Population (échelle log)', fontsize=12)
ax.set_xticks(years)
plt.xticks(rotation=45)
ax.set_yticks([1e3, 1e4, 1e5, 1e6])
ax.set_yticklabels(['1k', '10k', '100k', '1M'])
ax.legend(fontsize=11)

for x, y, text, color, xytext in annotations:
    ax.annotate(text, xy=(x, y), xytext=xytext,
                arrowprops=dict(facecolor=color, shrink=0.05, width=2),
                bbox=dict(boxstyle="round", alpha=0.1, color=color),
                fontsize=10)

for year, pop in zip(years, population):
    if year in key_years:
        ax.text(year, pop * 1.15, f"{pop:,}".replace(",", " "),
                ha='center', fontsize=9, fontweight='bold')

plt.tight_layout()
plt.savefig('cincinnati_population.png', dpi=300, bbox_inches='tight')
plt.show()

import matplotlib.pyplot as plt

# ============================================
# PARAMÈTRES - San Francisco, Californie
# ============================================
CITY_NAME = "San Francisco, Californie"
CITY_COLOR = '#f39c12'

years = [1848, 1850, 1860, 1870, 1880, 1890, 1900, 1906, 1910, 1920,
         1930, 1940, 1950, 1960, 1970, 1980, 1990, 2000, 2010, 2020]
population = [1000, 25000, 56802, 149473, 233959, 298997, 342782, 400000,
              416912, 506676, 634394, 634536, 775357, 740316, 715674, 678974,
              723959, 776733, 805235, 873965]

annotations = [
    (1850, 25000,   "⛏️ Gold Rush x25!",             'gold',   (1853, 80000)),
    (1906, 400000,  "🔥 Séisme+incendie",            'red',    (1895, 650000)),
    (1950, 775357,  "Pic WW2 + après-guerre",        'blue',   (1933, 900000)),
    (1980, 678974,  "Creux suburbanisation",         'red',    (1962, 400000)),
    (2020, 873965,  "💻 Tech boom",                  'green',  (2005, 400000)),
]

key_years = [1848, 2020]  # ← première et dernière dates seulement
# ============================================

fig, ax = plt.subplots(figsize=(14, 8))
plt.style.use('seaborn-v0_8')

ax.semilogy(years, population, marker='o', color=CITY_COLOR,
            linewidth=2.5, markersize=8, markerfacecolor='white', markeredgewidth=2)

# Zone Gold Rush
ax.axvspan(1848, 1855, alpha=0.15, color='gold', label='Gold Rush')
# Zone séisme
ax.axvspan(1904, 1908, alpha=0.15, color='red', label='Séisme 1906')
# Zone tech
ax.axvspan(1995, 2020, alpha=0.05, color='blue', label='Tech boom')

ax.grid(True, which="both", ls="-", alpha=0.2)
ax.set_title(f'Évolution démographique de {CITY_NAME}\nÉchelle logarithmique',
             fontsize=16, pad=20, fontweight='bold')
ax.set_xlabel('Année', fontsize=12)
ax.set_ylabel('Population (échelle log)', fontsize=12)
ax.set_xticks(years)
plt.xticks(rotation=45)
ax.set_yticks([1e3, 1e4, 1e5, 1e6])
ax.set_yticklabels(['1k', '10k', '100k', '1M'])
ax.legend(fontsize=11)

for x, y, text, color, xytext in annotations:
    ax.annotate(text, xy=(x, y), xytext=xytext,
                arrowprops=dict(facecolor=color, shrink=0.05, width=2),
                bbox=dict(boxstyle="round", alpha=0.1, color=color),
                fontsize=10)

# ✅ CORRECTION : toujours afficher première et dernière date
for year, pop in zip(years, population):
    if year in [years[0], years[-1]]:
        ax.text(year, pop * 1.15, f"{pop:,}".replace(",", " "),
                ha='center', fontsize=10, fontweight='bold', color='black',
                bbox=dict(boxstyle="round", alpha=0.2, color=CITY_COLOR))

plt.tight_layout()
plt.savefig('sanfrancisco_population.png', dpi=300, bbox_inches='tight')
plt.show()

import matplotlib.pyplot as plt

# ============================================
# PARAMÈTRES - Los Angeles, Californie
# ============================================
CITY_NAME = "Los Angeles, Californie"
CITY_COLOR = '#8e44ad'

years = [1850, 1860, 1870, 1880, 1890, 1900, 1910, 1920, 1930, 1940,
         1950, 1960, 1970, 1980, 1990, 2000, 2010, 2020]
population = [1610, 4385, 5728, 11183, 50395, 102479, 319198, 576673,
              1238048, 1504277, 1970358, 2479015, 2811801, 2966850,
              3485398, 3694820, 3792621, 3898747]

annotations = [
    (1890, 50395,   "🚂 Boom chemin de fer",         'brown',  (1865, 150000)),
    (1910, 319198,  "🎬 Naissance Hollywood",        'purple', (1893, 600000)),
    (1930, 1238048, "x4 en 20 ans!",                'red',    (1910, 2500000)),
    (1960, 2479015, "☀️ Boom automobile",            'orange', (1942, 4500000)),
    (2020, 3898747, "3ème ville USA",                'green',  (2000, 1500000)),
]

# ============================================

fig, ax = plt.subplots(figsize=(14, 8))
plt.style.use('seaborn-v0_8')

ax.semilogy(years, population, marker='o', color=CITY_COLOR,
            linewidth=2.5, markersize=8, markerfacecolor='white', markeredgewidth=2)

# Zone chemin de fer
ax.axvspan(1876, 1900, alpha=0.10, color='brown', label='Ère chemin de fer')
# Zone Hollywood / boom
ax.axvspan(1910, 1940, alpha=0.08, color='purple', label='Boom Hollywood')
# Zone automobile
ax.axvspan(1945, 1970, alpha=0.08, color='orange', label='Ère automobile')

ax.grid(True, which="both", ls="-", alpha=0.2)
ax.set_title(f'Évolution démographique de {CITY_NAME}\nÉchelle logarithmique',
             fontsize=16, pad=20, fontweight='bold')
ax.set_xlabel('Année', fontsize=12)
ax.set_ylabel('Population (échelle log)', fontsize=12)
ax.set_xticks(years)
plt.xticks(rotation=45)
ax.set_yticks([1e3, 1e4, 1e5, 1e6, 1e7])
ax.set_yticklabels(['1k', '10k', '100k', '1M', '10M'])
ax.legend(fontsize=11)

for x, y, text, color, xytext in annotations:
    ax.annotate(text, xy=(x, y), xytext=xytext,
                arrowprops=dict(facecolor=color, shrink=0.05, width=2),
                bbox=dict(boxstyle="round", alpha=0.1, color=color),
                fontsize=10)

# ✅ Première et dernière date
for year, pop in zip(years, population):
    if year in [years[0], years[-1]]:
        ax.text(year, pop * 1.15, f"{pop:,}".replace(",", " "),
                ha='center', fontsize=10, fontweight='bold', color='black',
                bbox=dict(boxstyle="round", alpha=0.2, color=CITY_COLOR))

plt.tight_layout()
plt.savefig('losangeles_population.png', dpi=300, bbox_inches='tight')
plt.show()

import matplotlib.pyplot as plt

# ============================================
# PARAMÈTRES - Des Moines, Iowa
# ============================================
CITY_NAME = "Des Moines, Iowa"
CITY_COLOR = '#27ae60'

years = [1850, 1860, 1870, 1880, 1890, 1900, 1910, 1920, 1930, 1940,
         1950, 1960, 1970, 1980, 1990, 2000, 2010, 2020]
population = [502, 3965, 12035, 22408, 50093, 62139, 86368, 126468,
              142559, 159819, 177965, 208982, 200587, 191003, 193187,
              198682, 203433, 214237]

annotations = [
    (1860, 3965,    "🏛️ Capitale de l'Iowa (1857)", 'blue',   (1862, 35000)),
    (1890, 50093,   "🌽 Boom agricole",              'green',  (1872, 80000)),
    (1920, 126468,  "📰 Hub assurance & finance",    'brown',  (1902, 160000)),
    (1960, 208982,  "Pic historique",                'black',  (1942, 230000)),
    (1980, 191003,  "📉 Déclin urbain",              'red',    (1963, 120000)),
    (2020, 214237,  "🔄 Reprise +5%",               'green',  (2003, 100000)),
]

# ============================================

fig, ax = plt.subplots(figsize=(14, 8))
plt.style.use('seaborn-v0_8')

ax.semilogy(years, population, marker='o', color=CITY_COLOR,
            linewidth=2.5, markersize=8, markerfacecolor='white', markeredgewidth=2)

# Zone croissance
ax.axvspan(1850, 1960, alpha=0.05, color='green', label='Ère croissance')
# Zone déclin
ax.axvspan(1960, 1990, alpha=0.08, color='red', label='Déclin urbain')
# Zone reprise
ax.axvspan(1990, 2020, alpha=0.05, color='blue', label='Reprise')

ax.grid(True, which="both", ls="-", alpha=0.2)
ax.set_title(f'Évolution démographique de {CITY_NAME}\nÉchelle logarithmique',
             fontsize=16, pad=20, fontweight='bold')
ax.set_xlabel('Année', fontsize=12)
ax.set_ylabel('Population (échelle log)', fontsize=12)
ax.set_xticks(years)
plt.xticks(rotation=45)
ax.set_yticks([1e3, 1e4, 1e5, 1e6])
ax.set_yticklabels(['1k', '10k', '100k', '1M'])
ax.legend(fontsize=11)

for x, y, text, color, xytext in annotations:
    ax.annotate(text, xy=(x, y), xytext=xytext,
                arrowprops=dict(facecolor=color, shrink=0.05, width=2),
                bbox=dict(boxstyle="round", alpha=0.1, color=color),
                fontsize=10)

# ✅ Première et dernière date
for year, pop in zip(years, population):
    if year in [years[0], years[-1]]:
        ax.text(year, pop * 1.15, f"{pop:,}".replace(",", " "),
                ha='center', fontsize=10, fontweight='bold', color='black',
                bbox=dict(boxstyle="round", alpha=0.2, color=CITY_COLOR))

plt.tight_layout()
plt.savefig('desmoines_population.png', dpi=300, bbox_inches='tight')
plt.show()

import matplotlib.pyplot as plt

# ============================================
# PARAMÈTRES - Miami, Floride
# ============================================
CITY_NAME = "Miami, Floride"
CITY_COLOR = '#e74c3c'

years = [1896, 1900, 1910, 1920, 1930, 1940, 1950, 1960, 1970, 1980,
         1990, 2000, 2010, 2020]
population = [444, 1681, 5471, 29571, 110637, 172172, 249276, 291688,
              334859, 346865, 358548, 362470, 399457, 442241]

annotations = [
    (1896, 444,    "🚂 Fondation Flagler",          'brown',  (1900, 3000)),
    (1920, 29571,  "🏖️ Boom immobilier x20!",       'orange', (1905, 80000)),
    (1930, 110637, "Krach 1929 ralentit",           'red',    (1912, 200000)),
    (1960, 291688, "🇨🇺 Exil cubain",               'blue',   (1943, 400000)),
    (2020, 442241, "🌴 Hub Amérique Latine",        'green',  (2003, 200000)),
]

# ============================================

fig, ax = plt.subplots(figsize=(14, 8))
plt.style.use('seaborn-v0_8')

ax.semilogy(years, population, marker='o', color=CITY_COLOR,
            linewidth=2.5, markersize=8, markerfacecolor='white', markeredgewidth=2)

# Zone boom immobilier
ax.axvspan(1920, 1930, alpha=0.12, color='orange', label='Boom immobilier')
# Zone immigration cubaine
ax.axvspan(1959, 1980, alpha=0.08, color='blue', label='Immigration cubaine')
# Zone croissance moderne
ax.axvspan(2000, 2020, alpha=0.06, color='green', label='Croissance moderne')

ax.grid(True, which="both", ls="-", alpha=0.2)
ax.set_title(f'Évolution démographique de {CITY_NAME}\nÉchelle logarithmique',
             fontsize=16, pad=20, fontweight='bold')
ax.set_xlabel('Année', fontsize=12)
ax.set_ylabel('Population (échelle log)', fontsize=12)
ax.set_xticks(years)
plt.xticks(rotation=45)
ax.set_yticks([1e2, 1e3, 1e4, 1e5, 1e6])
ax.set_yticklabels(['100', '1k', '10k', '100k', '1M'])
ax.legend(fontsize=11)

for x, y, text, color, xytext in annotations:
    ax.annotate(text, xy=(x, y), xytext=xytext,
                arrowprops=dict(facecolor=color, shrink=0.05, width=2),
                bbox=dict(boxstyle="round", alpha=0.1, color=color),
                fontsize=10)

# ✅ Première et dernière date
for year, pop in zip(years, population):
    if year in [years[0], years[-1]]:
        ax.text(year, pop * 1.15, f"{pop:,}".replace(",", " "),
                ha='center', fontsize=10, fontweight='bold', color='black',
                bbox=dict(boxstyle="round", alpha=0.2, color=CITY_COLOR))

plt.tight_layout()
plt.savefig('miami_population.png', dpi=300, bbox_inches='tight')
plt.show()

import matplotlib.pyplot as plt
CITY_NAME = "Salt Lake City, Utah"
CITY_COLOR = '#2980b9'

years = [1847, 1848, 1849, 1850, 1860, 1870, 1880, 1890, 1900, 1910,
         1920, 1930, 1940, 1950, 1960, 1970, 1980, 1990, 2000, 2010, 2020]
population = [148, 1500, 5000, 6157, 8236, 12854, 20768, 44843, 53531,
              92777, 118110, 140267, 149934, 182121, 189454, 175885,
              163033, 159936, 181743, 186440, 199723]

annotations = [
    (1847, 148,    "⛪ 148 pionniers Mormons",      'purple', (1852, 800)),
    (1849, 5000,   "🌊 Migration massive",          'blue',   (1853, 15000)),
    (1890, 44843,  "⛏️ Boom minier Bingham",        'gray',   (1873, 70000)),
    (1910, 92777,  "🚂 Boom chemin de fer",         'brown',  (1893, 130000)),
    (1950, 182121, "🏭 Industrie WW2",              'green',  (1933, 210000)),
    (1960, 189454, "📍 Pic historique",             'black',  (1943, 230000)),
    (1990, 159936, "📉 Creux suburbanisation",      'red',    (1972, 120000)),
    (2000, 181743, "🏔️ JO Hiver 2002",             'cyan',   (1983, 90000)),
    (2020, 199723, "💻 Silicon Slopes",             'green',  (2004, 70000)),
]

fig, ax = plt.subplots(figsize=(15, 9))
plt.style.use('seaborn-v0_8')

ax.semilogy(years, population, marker='o', color=CITY_COLOR,
            linewidth=2.5, markersize=8, markerfacecolor='white',
            markeredgewidth=2, markeredgecolor=CITY_COLOR)

ax.axvspan(1847, 1850, alpha=0.15, color='purple', label='Fondation pionniers')
ax.axvspan(1880, 1910, alpha=0.08, color='gray',   label='Boom minier & ferroviaire')
ax.axvspan(1960, 1990, alpha=0.08, color='red',    label='Déclin & suburbanisation')
ax.axvspan(1990, 2020, alpha=0.05, color='green',  label='Renaissance tech')

ax.grid(True, which="both", ls="-", alpha=0.2)
ax.set_title(f'Évolution démographique de {CITY_NAME}\n'
             f'De 148 pionniers (1847) à 200k habitants (2020)',
             fontsize=16, pad=20, fontweight='bold')
ax.set_xlabel('Année', fontsize=12)
ax.set_ylabel('Population (échelle log)', fontsize=12)
ax.set_xticks(years)
plt.xticks(rotation=45)
ax.set_yticks([1e2, 1e3, 1e4, 1e5, 1e6])
ax.set_yticklabels(['100', '1k', '10k', '100k', '1M'])
ax.legend(fontsize=10, loc='upper left')

for x, y, text, color, xytext in annotations:
    ax.annotate(text, xy=(x, y), xytext=xytext,
                arrowprops=dict(facecolor=color, shrink=0.05, width=1.5),
                bbox=dict(boxstyle="round", alpha=0.1, color=color),
                fontsize=9)

for year, pop in zip(years, population):
    if year in [1847, 2020]:
        ax.text(year, pop * 1.4,
                f"{pop:,}".replace(",", " "),
                ha='center', fontsize=10, fontweight='bold',
                bbox=dict(boxstyle="round", alpha=0.2, color=CITY_COLOR))

plt.tight_layout()
plt.savefig('saltlakecity_population_detail.png', dpi=300, bbox_inches='tight')
plt.show()

import matplotlib.pyplot as plt
import numpy as np

CITY_NAME = "Las Vegas, Nevada"
CITY_COLOR = '#FF6B35'

years = [1900, 1910, 1920, 1930, 1940, 1950, 1960, 1970, 1980, 1990, 2000, 2010, 2020]
population = [30, 30, 2686, 5165, 8422, 24624, 64405, 125787, 164674, 258295, 478434, 583756, 641903]

annotations = [
    (1900, 30,     "🏜️ Village désertique",         'brown',  (1905, 200)),
    (1930, 5165,   "🎲 Légalisation du jeu (1931)",  'gold',   (1918, 1500)),
    (1940, 8422,   "🏨 El Rancho 1er casino (1941)", 'orange', (1926, 5000)),
    (1950, 24624,  "💣 Base atomique Nevada",        'red',    (1935, 15000)),
    (1960, 64405,  "🎰 Boom Strip casinos",          'purple', (1943, 40000)),
    (1990, 258295, "🏙️ Méga-resorts",               'blue',   (1972, 150000)),
    (2000, 478434, "🌆 Ville la + rapide USA",       'green',  (1983, 350000)),
    (2020, 641903, "💻 Diversification économique",  'cyan',   (2005, 550000)),
]

fig, ax = plt.subplots(figsize=(15, 9))
plt.style.use('seaborn-v0_8')

ax.semilogy(years, population, marker='o', color=CITY_COLOR,
            linewidth=2.5, markersize=8, markerfacecolor='white',
            markeredgewidth=2, markeredgecolor=CITY_COLOR)

ax.axvspan(1931, 1941, alpha=0.15, color='gold',   label='Légalisation jeu')
ax.axvspan(1941, 1960, alpha=0.08, color='orange', label='Boom casinos & guerre')
ax.axvspan(1960, 2000, alpha=0.08, color='purple', label='Explosion Strip')
ax.axvspan(2000, 2020, alpha=0.05, color='green',  label='Diversification')

ax.grid(True, which="both", ls="-", alpha=0.2)
ax.set_title(f'Évolution démographique de {CITY_NAME}\n'
             f'De 30 habitants (1900) à 641 903 habitants (2020) — Facteur ×21 400',
             fontsize=16, pad=20, fontweight='bold')
ax.set_xlabel('Année', fontsize=12)
ax.set_ylabel('Population (échelle log)', fontsize=12)
ax.set_xticks(years)
plt.xticks(rotation=45)
ax.set_yticks([1e1, 1e2, 1e3, 1e4, 1e5, 1e6])
ax.set_yticklabels(['10', '100', '1k', '10k', '100k', '1M'])
ax.legend(fontsize=10, loc='upper left')

for x, y, text, color, xytext in annotations:
    ax.annotate(text, xy=(x, y), xytext=xytext,
                arrowprops=dict(facecolor=color, shrink=0.05, width=1.5),
                bbox=dict(boxstyle="round", alpha=0.1, color=color),
                fontsize=9)

for year, pop in zip(years, population):
    if year in [1900, 2020]:
        ax.text(year, pop * 1.4,
                f"{pop:,}".replace(",", " "),
                ha='center', fontsize=10, fontweight='bold',
                bbox=dict(boxstyle="round", alpha=0.2, color=CITY_COLOR))

plt.tight_layout()
plt.savefig('lasvegas_population.png', dpi=300, bbox_inches='tight')
plt.show()

import matplotlib.pyplot as plt
import numpy as np

CITY_NAME = "Phoenix, Arizona"
CITY_COLOR = '#C1440E'

years = [1880, 1890, 1900, 1910, 1920, 1930, 1940, 1950, 1960, 1970, 1980, 1990, 2000, 2010, 2020]
population = [1708, 3152, 5544, 11134, 29053, 48118, 65414, 106818, 439170, 584303, 789704, 983403, 1321045, 1445632, 1608139]

annotations = [
    (1880, 1708,    "🌵 Fondation Phoenix",           'brown',  (1885, 400)),
    (1910, 11134,   "💧 Roosevelt Dam (1911)",        'blue',   (1895, 3000)),
    (1920, 29053,   "🚂 Boom chemin de fer",           'brown',  (1905, 12000)),
    (1950, 106818,  "❄️ Air conditionné révolution",  'cyan',   (1932, 50000)),
    (1960, 439170,  "☀️ Explosion Sun Belt",           'orange', (1942, 200000)),
    (1970, 584303,  "🏗️ Suburbanisation massive",     'gray',   (1953, 400000)),
    (2000, 1321045, "💼 Boom tech & retraités",        'green',  (1983, 900000)),
    (2020, 1608139, "🌆 5e ville USA",                'purple', (2006, 1400000)),
]

fig, ax = plt.subplots(figsize=(15, 9))
plt.style.use('seaborn-v0_8')

ax.semilogy(years, population, marker='o', color=CITY_COLOR,
            linewidth=2.5, markersize=8, markerfacecolor='white',
            markeredgewidth=2, markeredgecolor=CITY_COLOR)

ax.axvspan(1908, 1915, alpha=0.15, color='blue',   label='Roosevelt Dam & eau')
ax.axvspan(1945, 1965, alpha=0.10, color='cyan',   label='Air conditionné & Sun Belt')
ax.axvspan(1965, 1990, alpha=0.08, color='orange', label='Suburbanisation')
ax.axvspan(1990, 2020, alpha=0.05, color='green',  label='Tech & croissance continue')

ax.grid(True, which="both", ls="-", alpha=0.2)
ax.set_title(f'Évolution démographique de {CITY_NAME}\n'
             f'De 1 708 habitants (1880) à 1 608 139 habitants (2020) — Facteur ×290',
             fontsize=16, pad=20, fontweight='bold')
ax.set_xlabel('Année', fontsize=12)
ax.set_ylabel('Population (échelle log)', fontsize=12)
ax.set_xticks(years)
plt.xticks(rotation=45)
ax.set_yticks([1e3, 1e4, 1e5, 1e6, 1e7])
ax.set_yticklabels(['1k', '10k', '100k', '1M', '10M'])
ax.legend(fontsize=10, loc='upper left')

for x, y, text, color, xytext in annotations:
    ax.annotate(text, xy=(x, y), xytext=xytext,
                arrowprops=dict(facecolor=color, shrink=0.05, width=1.5),
                bbox=dict(boxstyle="round", alpha=0.1, color=color),
                fontsize=9)

for year, pop in zip(years, population):
    if year in [1880, 2020]:
        ax.text(year, pop * 1.4,
                f"{pop:,}".replace(",", " "),
                ha='center', fontsize=10, fontweight='bold',
                bbox=dict(boxstyle="round", alpha=0.2, color=CITY_COLOR))

plt.tight_layout()
plt.savefig('phoenix_population.png', dpi=300, bbox_inches='tight')
plt.show()

import matplotlib.pyplot as plt
import numpy as np

CITY_NAME = "Houston, Texas"
CITY_COLOR = '#2E86AB'

years = [1850, 1860, 1870, 1880, 1890, 1900, 1910, 1920, 1930, 1940, 1950, 1960, 1970, 1980, 1990, 2000, 2010, 2020]
population = [2396, 4845, 9382, 16513, 27557, 44633, 78800, 138276, 292352, 384514, 596163, 938219, 1232802, 1595138, 1630553, 1953631, 2099451, 2304580]

annotations = [
    (1850, 2396,    "⚓ Port de Houston fondé",       'brown',  (1854, 700)),
    (1900, 44633,   "🛢️ Pétrole Spindletop 1901",    'black',  (1883, 20000)),
    (1910, 78800,   "🚢 Canal maritime ouvert (1914)",'blue',   (1896, 55000)),
    (1930, 292352,  "⚗️ Boom pétrochimique",          'orange', (1910, 150000)),
    (1960, 938219,  "🚀 NASA Johnson Center (1961)",  'cyan',   (1943, 500000)),
    (1980, 1595138, "💰 Boom pétrolier maximal",      'green',  (1963, 1100000)),
    (1990, 1630553, "📉 Crise pétrole -1986",         'red',    (1972, 1700000)),
    (2020, 2304580, "🌍 Ville la + diverse USA",      'purple', (2005, 2000000)),
]

fig, ax = plt.subplots(figsize=(15, 9))
plt.style.use('seaborn-v0_8')

ax.semilogy(years, population, marker='o', color=CITY_COLOR,
            linewidth=2.5, markersize=8, markerfacecolor='white',
            markeredgewidth=2, markeredgecolor=CITY_COLOR)

ax.axvspan(1900, 1915, alpha=0.15, color='black',  label='Pétrole & canal maritime')
ax.axvspan(1940, 1965, alpha=0.08, color='cyan',   label='WW2 & NASA')
ax.axvspan(1965, 1985, alpha=0.08, color='green',  label='Boom pétrolier')
ax.axvspan(1985, 1995, alpha=0.08, color='red',    label='Crise pétrole')

ax.grid(True, which="both", ls="-", alpha=0.2)
ax.set_title(f'Évolution démographique de {CITY_NAME}\n'
             f'De 2 396 habitants (1850) à 2 304 580 habitants (2020) — Facteur ×52',
             fontsize=16, pad=20, fontweight='bold')
ax.set_xlabel('Année', fontsize=12)
ax.set_ylabel('Population (échelle log)', fontsize=12)
ax.set_xticks(years)
plt.xticks(rotation=45)
ax.set_yticks([1e3, 1e4, 1e5, 1e6, 1e7])
ax.set_yticklabels(['1k', '10k', '100k', '1M', '10M'])
ax.legend(fontsize=10, loc='upper left')

for x, y, text, color, xytext in annotations:
    ax.annotate(text, xy=(x, y), xytext=xytext,
                arrowprops=dict(facecolor=color, shrink=0.05, width=1.5),
                bbox=dict(boxstyle="round", alpha=0.1, color=color),
                fontsize=9)

for year, pop in zip(years, population):
    if year in [1850, 2020]:
        ax.text(year, pop * 1.4,
                f"{pop:,}".replace(",", " "),
                ha='center', fontsize=10, fontweight='bold',
                bbox=dict(boxstyle="round", alpha=0.2, color=CITY_COLOR))

plt.tight_layout()
plt.savefig('houston_population.png', dpi=300, bbox_inches='tight')
plt.show()

import matplotlib.pyplot as plt
import numpy as np

CITY_NAME = "Detroit, Michigan"
CITY_COLOR = '#1B4F72'

years = [1820, 1830, 1840, 1850, 1860, 1870, 1880, 1890, 1900, 1910,
         1920, 1930, 1940, 1950, 1960, 1970, 1980, 1990, 2000, 2010, 2020]
population = [1422, 2222, 9102, 21019, 45619, 79577, 116340, 205876,
              285704, 465766, 993678, 1568662, 1623452, 1849568, 1670144,
              1511482, 1203339, 1027974, 951270, 713777, 639111]

annotations = [
    (1820, 1422,    "⚓ Village frontier",             'brown',  (1826, 400)),
    (1870, 79577,   "⚙️ Industrie cuivre & bois",     'gray',   (1845, 40000)),
    (1900, 285704,  "🚗 Ford Motor Company (1903)",   'blue',   (1882, 150000)),
    (1920, 993678,  "🏭 Capital mondiale auto",        'black',  (1905, 600000)),
    (1950, 1849568, "📍 Pic historique",              'green',  (1932, 1500000)),
    (1970, 1511482, "🔥 Émeutes raciales (1967)",     'red',    (1945, 2100000)),
    (1980, 1203339, "📉 Déclin industrie auto",        'orange', (1962, 2300000)),
    (2010, 713777,  "💸 Faillite municipale (2013)",  'red',    (1993, 2100000)),
    (2020, 639111,  "🔨 Tentative renaissance",        'cyan',   (2003, 1800000)),
]

fig, ax = plt.subplots(figsize=(15, 9))
plt.style.use('seaborn-v0_8')

ax.semilogy(years, population, marker='o', color=CITY_COLOR,
            linewidth=2.5, markersize=8, markerfacecolor='white',
            markeredgewidth=2, markeredgecolor=CITY_COLOR)

ax.axvspan(1900, 1910, alpha=0.15, color='blue',   label='Naissance industrie auto')
ax.axvspan(1910, 1950, alpha=0.08, color='gray',   label='Âge d\'or automobile')
ax.axvspan(1950, 1980, alpha=0.08, color='orange', label='Début du déclin')
ax.axvspan(1980, 2020, alpha=0.10, color='red',    label='Effondrement démographique')

ax.grid(True, which="both", ls="-", alpha=0.2)
ax.set_title(f'Évolution démographique de {CITY_NAME}\n'
             f'De 1 422 habitants (1820) à 639 111 habitants (2020) — Pic 1 849 568 en 1950',
             fontsize=16, pad=20, fontweight='bold')
ax.set_xlabel('Année', fontsize=12)
ax.set_ylabel('Population (échelle log)', fontsize=12)
ax.set_xticks(years)
plt.xticks(rotation=45)
ax.set_yticks([1e3, 1e4, 1e5, 1e6, 1e7])
ax.set_yticklabels(['1k', '10k', '100k', '1M', '10M'])
ax.legend(fontsize=10, loc='upper left')

for x, y, text, color, xytext in annotations:
    ax.annotate(text, xy=(x, y), xytext=xytext,
                arrowprops=dict(facecolor=color, shrink=0.05, width=1.5),
                bbox=dict(boxstyle="round", alpha=0.1, color=color),
                fontsize=9)

for year, pop in zip(years, population):
    if year in [1820, 1950, 2020]:
        ax.text(year, pop * 1.4,
                f"{pop:,}".replace(",", " "),
                ha='center', fontsize=10, fontweight='bold',
                bbox=dict(boxstyle="round", alpha=0.2, color=CITY_COLOR))

plt.tight_layout()
plt.savefig('detroit_population.png', dpi=300, bbox_inches='tight')
plt.show()

import matplotlib.pyplot as plt
import numpy as np

CITY_NAME = "Chicago, Illinois"
CITY_COLOR = '#17202A'

years = [1833, 1840, 1850, 1860, 1870, 1880, 1890, 1900, 1910, 1920,
         1930, 1940, 1950, 1960, 1970, 1980, 1990, 2000, 2010, 2020]
population = [350, 4470, 29963, 112172, 298977, 503185, 1099850, 1698575,
              2185283, 2701705, 3376438, 3396808, 3620962, 3550404, 3366957,
              3005072, 2783726, 2896016, 2695598, 2696555]

annotations = [
    (1833, 350,     "🏕️ Incorporation village",       'brown',  (1838, 150)),
    (1850, 29963,   "🚂 Carrefour ferroviaire",        'gray',   (1843, 8000)),
    (1870, 298977,  "🔥 Grand incendie (1871)",        'red',    (1857, 100000)),
    (1890, 1099850, "🌍 Expo Universelle 1893",        'purple', (1875, 600000)),
    (1900, 1698575, "🥩 Capitale mondiale viande",     'brown',  (1883, 1200000)),
    (1920, 2701705, "🎷 Great Migration jazz",         'gold',   (1905, 2000000)),
    (1950, 3620962, "📍 Pic historique",              'green',  (1932, 3000000)),
    (1970, 3366957, "✊ Émeutes Convention Démo. (1968)",'red',   (1952, 4200000)),
    (1980, 3005072, "📉 Désindustrialisation",         'orange', (1963, 4400000)),
    (2020, 2696555, "💻 Hub finance & tech",           'blue',   (2003, 3800000)),
]

fig, ax = plt.subplots(figsize=(15, 9))
plt.style.use('seaborn-v0_8')

ax.semilogy(years, population, marker='o', color=CITY_COLOR,
            linewidth=2.5, markersize=8, markerfacecolor='white',
            markeredgewidth=2, markeredgecolor=CITY_COLOR)

ax.axvspan(1833, 1871, alpha=0.15, color='gray',   label='Fondation & rail')
ax.axvspan(1871, 1920, alpha=0.08, color='orange', label='Reconstruction & boom')
ax.axvspan(1920, 1950, alpha=0.08, color='gold',   label='Âge d\'or Chicago')
ax.axvspan(1950, 2020, alpha=0.08, color='red',    label='Déclin progressif')

ax.grid(True, which="both", ls="-", alpha=0.2)
ax.set_title(f'Évolution démographique de {CITY_NAME}\n'
             f'De 350 habitants (1833) à 2 696 555 habitants (2020) — Pic 3 620 962 en 1950',
             fontsize=16, pad=20, fontweight='bold')
ax.set_xlabel('Année', fontsize=12)
ax.set_ylabel('Population (échelle log)', fontsize=12)
ax.set_xticks(years)
plt.xticks(rotation=45)
ax.set_yticks([1e2, 1e3, 1e4, 1e5, 1e6, 1e7])
ax.set_yticklabels(['100', '1k', '10k', '100k', '1M', '10M'])
ax.legend(fontsize=10, loc='upper left')

for x, y, text, color, xytext in annotations:
    ax.annotate(text, xy=(x, y), xytext=xytext,
                arrowprops=dict(facecolor=color, shrink=0.05, width=1.5),
                bbox=dict(boxstyle="round", alpha=0.1, color=color),
                fontsize=9)

for year, pop in zip(years, population):
    if year in [1833, 1950, 2020]:
        ax.text(year, pop * 1.4,
                f"{pop:,}".replace(",", " "),
                ha='center', fontsize=10, fontweight='bold',
                bbox=dict(boxstyle="round", alpha=0.2, color=CITY_COLOR))

plt.tight_layout()
plt.savefig('chicago_population.png', dpi=300, bbox_inches='tight')
plt.show()

import matplotlib.pyplot as plt
import numpy as np

CITY_NAME = "Philadelphia, Pennsylvania"
CITY_COLOR = '#922B21'

years = [1700, 1720, 1740, 1760, 1776, 1790, 1800, 1810, 1820, 1830,
         1840, 1850, 1860, 1870, 1880, 1890, 1900, 1910, 1920, 1930,
         1940, 1950, 1960, 1970, 1980, 1990, 2000, 2010, 2020]
population = [2450, 5000, 8000, 18000, 40000, 44096, 61559, 91874, 112772,
              161271, 220423, 340045, 565529, 674022, 847170, 1046964,
              1293697, 1549008, 1823779, 1950961, 1931334, 2071605,
              2002512, 1948609, 1688210, 1585577, 1517550, 1526006, 1603797]

annotations = [
    (1700, 2450,    "🏛️ Fondation W. Penn 1682",      'brown',  (1706, 800)),
    (1776, 40000,   "🔔 Capitale révolution USA",      'blue',   (1750, 12000)),
    (1790, 44096,   "🇺🇸 1ère capitale fédérale",      'red',    (1760, 25000)),
    (1850, 340045,  "⚙️ Révolution industrielle",      'gray',   (1825, 150000)),
    (1880, 847170,  "🎉 Centenaire USA expo (1876)",   'purple', (1842, 400000)),
    (1910, 1549008, "🏭 Boom industrie lourde",        'black',  (1893, 1000000)),
    (1950, 2071605, "📍 Pic historique",              'green',  (1932, 1700000)),
    (1960, 2002512, "✊ Émeutes raciales (1964)",      'red',    (1943, 2400000)),
    (1980, 1688210, "📉 Désindustrialisation",         'orange', (1963, 2600000)),
    (2020, 1603797, "🎓 Hub santé & éducation",        'cyan',   (2003, 2200000)),
]

fig, ax = plt.subplots(figsize=(15, 9))
plt.style.use('seaborn-v0_8')

ax.semilogy(years, population, marker='o', color=CITY_COLOR,
            linewidth=2.5, markersize=8, markerfacecolor='white',
            markeredgewidth=2, markeredgecolor=CITY_COLOR)

ax.axvspan(1682, 1800, alpha=0.15, color='blue',   label='Ère coloniale & révolution')
ax.axvspan(1800, 1920, alpha=0.08, color='gray',   label='Industrialisation')
ax.axvspan(1920, 1950, alpha=0.08, color='gold',   label='Âge d\'or Philadelphia')
ax.axvspan(1950, 2020, alpha=0.08, color='red',    label='Déclin & stabilisation')

ax.grid(True, which="both", ls="-", alpha=0.2)
ax.set_title(f'Évolution démographique de {CITY_NAME}\n'
             f'De 2 450 habitants (1700) à 1 603 797 habitants (2020) — Pic 2 071 605 en 1950',
             fontsize=16, pad=20, fontweight='bold')
ax.set_xlabel('Année', fontsize=12)
ax.set_ylabel('Population (échelle log)', fontsize=12)
ax.set_xticks(years)
plt.xticks(rotation=45)
ax.set_yticks([1e3, 1e4, 1e5, 1e6, 1e7])
ax.set_yticklabels(['1k', '10k', '100k', '1M', '10M'])
ax.legend(fontsize=10, loc='upper left')

for x, y, text, color, xytext in annotations:
    ax.annotate(text, xy=(x, y), xytext=xytext,
                arrowprops=dict(facecolor=color, shrink=0.05, width=1.5),
                bbox=dict(boxstyle="round", alpha=0.1, color=color),
                fontsize=9)

for year, pop in zip(years, population):
    if year in [1700, 1950, 2020]:
        ax.text(year, pop * 1.4,
                f"{pop:,}".replace(",", " "),
                ha='center', fontsize=10, fontweight='bold',
                bbox=dict(boxstyle="round", alpha=0.2, color=CITY_COLOR))

plt.tight_layout()
plt.savefig('philadelphia_population.png', dpi=300, bbox_inches='tight')
plt.show()

import matplotlib.pyplot as plt
import numpy as np

CITY_NAME = "Washington, District of Columbia"
CITY_COLOR = '#1A5276'

years = [1800, 1810, 1820, 1830, 1840, 1850, 1860, 1870, 1880, 1890,
         1900, 1910, 1920, 1930, 1940, 1950, 1960, 1970, 1980, 1990,
         2000, 2010, 2020]
population = [8144, 15471, 23336, 30261, 43712, 51687, 75080, 109199,
              177624, 230392, 278718, 331069, 437571, 486869, 663091,
              802178, 763956, 756510, 638333, 606900, 572059, 601723, 689545]

annotations = [
    (1800, 8144,   "🏗️ Capitale inaugurée 1800",      'brown',  (1803, 2500)),
    (1810, 15471,  "🔥 Incendie britannique (1814)",   'red',    (1806, 8000)),
    (1860, 75080,  "⚔️ Guerre Civile — hub Union (1861)", 'gray', (1840, 35000)),
    (1900, 278718, "🏛️ Expansion fédérale",           'blue',   (1882, 180000)),
    (1930, 486869, "💼 New Deal — explosion fonct. (1933)", 'gold', (1910, 380000)),
    (1940, 663091, "✈️ WWII — boom fédéral",          'green',  (1920, 550000)),
    (1950, 802178, "📍 Pic historique",               'green',  (1932, 950000)),
    (1970, 756510, "✊ Émeutes assassinat MLK (1968)", 'red',    (1952, 1100000)),
    (1980, 638333, "📉 Crise urbaine & criminalité",   'orange', (1963, 1200000)),
    (2000, 572059, "📉 Creux démographique",           'red',    (1983, 1100000)),
    (2020, 689545, "📈 Gentrification & renaissance",  'cyan',   (2005, 900000)),
]

fig, ax = plt.subplots(figsize=(15, 9))
plt.style.use('seaborn-v0_8')

ax.semilogy(years, population, marker='o', color=CITY_COLOR,
            linewidth=2.5, markersize=8, markerfacecolor='white',
            markeredgewidth=2, markeredgecolor=CITY_COLOR)

ax.axvspan(1800, 1861, alpha=0.15, color='blue',   label='Jeune capitale fédérale')
ax.axvspan(1861, 1865, alpha=0.25, color='red',    label='Guerre Civile')
ax.axvspan(1933, 1950, alpha=0.10, color='gold',   label='New Deal & WWII boom')
ax.axvspan(1950, 2000, alpha=0.08, color='orange', label='Déclin urbain')
ax.axvspan(2000, 2020, alpha=0.08, color='green',  label='Renaissance')

ax.grid(True, which="both", ls="-", alpha=0.2)
ax.set_title(f'Évolution démographique de {CITY_NAME}\n'
             f'De 8 144 habitants (1800) à 689 545 habitants (2020) — Pic 802 178 en 1950',
             fontsize=16, pad=20, fontweight='bold')
ax.set_xlabel('Année', fontsize=12)
ax.set_ylabel('Population (échelle log)', fontsize=12)
ax.set_xticks(years)
plt.xticks(rotation=45)
ax.set_yticks([1e3, 1e4, 1e5, 1e6])
ax.set_yticklabels(['1k', '10k', '100k', '1M'])
ax.legend(fontsize=10, loc='upper left')

for x, y, text, color, xytext in annotations:
    ax.annotate(text, xy=(x, y), xytext=xytext,
                arrowprops=dict(facecolor=color, shrink=0.05, width=1.5),
                bbox=dict(boxstyle="round", alpha=0.1, color=color),
                fontsize=9)

for year, pop in zip(years, population):
    if year in [1800, 1950, 2000, 2020]:
        ax.text(year, pop * 1.4,
                f"{pop:,}".replace(",", " "),
                ha='center', fontsize=10, fontweight='bold',
                bbox=dict(boxstyle="round", alpha=0.2, color=CITY_COLOR))

plt.tight_layout()
plt.savefig('washington_dc_population.png', dpi=300, bbox_inches='tight')
plt.show()

import matplotlib.pyplot as plt
import numpy as np

CITY_NAME = "Newark, New Jersey"
CITY_COLOR = '#1E8449'

years = [1800, 1810, 1820, 1830, 1840, 1850, 1860, 1870, 1880, 1890,
         1900, 1910, 1920, 1930, 1940, 1950, 1960, 1967, 1970, 1980,
         1990, 2000, 2010, 2020]
population = [6507, 7914, 9887, 10953, 17290, 38894, 71941, 105059,
              136508, 181830, 246070, 347469, 414216, 442337, 429760,
              438776, 405220, 400000, 381930, 329248, 275221, 273546,
              277140, 311549]

annotations = [
    (1800, 6507,   "🏭 Centre cuir & joaillerie",     'brown',  (1803, 2000)),
    (1850, 38894,  "⚙️ Révolution industrielle",      'gray',   (1832, 20000)),
    (1870, 105059, "🔧 Hub manufacturier NJ",         'blue',   (1852, 60000)),
    (1910, 347469, "🌊 Vague immigration europ.",     'purple', (1892, 220000)),
    (1930, 442337, "📍 Pic historique",              'green',  (1912, 500000)),
    (1967, 400000, "🔥 Émeutes 1967 — tournant",     'red',    (1945, 600000)),
    (1980, 329248, "📉 Fuite des blancs & industrie", 'orange', (1952, 700000)),
    (1990, 275221, "💊 Crise crack & criminalité",    'black',  (1970, 700000)),
    (2010, 277140, "🔄 Légère stabilisation",         'teal',   (1992, 500000)),
    (2020, 311549, "📈 Renaissance & gentrification", 'cyan',   (2003, 450000)),
]

fig, ax = plt.subplots(figsize=(15, 9))
plt.style.use('seaborn-v0_8')

ax.semilogy(years, population, marker='o', color=CITY_COLOR,
            linewidth=2.5, markersize=8, markerfacecolor='white',
            markeredgewidth=2, markeredgecolor=CITY_COLOR)

ax.axvspan(1800, 1870, alpha=0.15, color='gray',   label='Ère industrielle naissante')
ax.axvspan(1870, 1930, alpha=0.08, color='blue',   label='Boom immigration & industrie')
ax.axvspan(1930, 1967, alpha=0.08, color='gold',   label='Apogée & tensions')
ax.axvspan(1967, 1967, alpha=0.50, color='red',    label='Émeutes 1967')
ax.axvspan(1967, 2000, alpha=0.08, color='red',    label='Déclin post-émeutes')
ax.axvspan(2000, 2020, alpha=0.08, color='green',  label='Stabilisation & reprise')

ax.grid(True, which="both", ls="-", alpha=0.2)
ax.set_title(f'Évolution démographique de {CITY_NAME}\n'
             f'De 6 507 habitants (1800) à 311 549 habitants (2020) — Pic 442 337 en 1930',
             fontsize=16, pad=20, fontweight='bold')
ax.set_xlabel('Année', fontsize=12)
ax.set_ylabel('Population (échelle log)', fontsize=12)
ax.set_xticks(years)
plt.xticks(rotation=45)
ax.set_yticks([1e3, 1e4, 1e5, 1e6])
ax.set_yticklabels(['1k', '10k', '100k', '1M'])
ax.legend(fontsize=10, loc='upper left')

for x, y, text, color, xytext in annotations:
    ax.annotate(text, xy=(x, y), xytext=xytext,
                arrowprops=dict(facecolor=color, shrink=0.05, width=1.5),
                bbox=dict(boxstyle="round", alpha=0.1, color=color),
                fontsize=9)

for year, pop in zip(years, population):
    if year in [1800, 1930, 1990, 2020]:
        ax.text(year, pop * 1.4,
                f"{pop:,}".replace(",", " "),
                ha='center', fontsize=10, fontweight='bold',
                bbox=dict(boxstyle="round", alpha=0.2, color=CITY_COLOR))

plt.tight_layout()
plt.savefig('newark_nj_population.png', dpi=300, bbox_inches='tight')
plt.show()

import matplotlib.pyplot as plt
import numpy as np

CITY_NAME = "Seattle, Washington"
CITY_COLOR = '#1A5276'

years = [1860, 1870, 1880, 1890, 1900, 1910, 1920, 1930, 1940, 1950,
         1960, 1970, 1980, 1990, 2000, 2010, 2020]
population = [302, 1107, 3553, 42837, 80671, 237194, 315312, 365583,
              368302, 467591, 557087, 530831, 493846, 516259,
              563374, 608660, 737255]

annotations = [
    (1860, 302,    "🪵 Camp de bûcherons fondé",        'brown',  (1861, 100)),
    (1890, 42837,  "🔥 Grand incendie 1889 — reconstruction", 'red', (1871, 25000)),
    (1900, 80671,  "⛏️ Ruée vers l'or Klondike (1897)", 'gold',   (1878, 50000)),
    (1910, 237194, "🚢 Hub Pacifique & immigration",    'blue',   (1892, 150000)),
    (1940, 368302, "✈️ Boeing — WWII production",       'gray',   (1922, 550000)),
    (1950, 467591, "🛩️ Boom Boeing post-guerre",        'purple', (1932, 700000)),
    (1970, 530831, "📉 Boeing Bust — 1971",             'orange', (1952, 800000)),
    (1980, 493846, "😟 Panneau : Last one out...",      'black',  (1962, 800000)),
    (2000, 563374, "💻 Microsoft & Amazon arrivent",    'teal',   (1982, 800000)),
    (2020, 737255, "🚀 Tech boom — ville transformée",  'cyan',   (2003, 900000)),
]

fig, ax = plt.subplots(figsize=(15, 9))
plt.style.use('seaborn-v0_8')

ax.semilogy(years, population, marker='o', color=CITY_COLOR,
            linewidth=2.5, markersize=8, markerfacecolor='white',
            markeredgewidth=2, markeredgecolor=CITY_COLOR)

ax.axvspan(1860, 1900, alpha=0.15, color='brown', label='Ère bois & ruée or')
ax.axvspan(1900, 1940, alpha=0.08, color='blue',  label='Hub maritime & Boeing naissant')
ax.axvspan(1940, 1970, alpha=0.08, color='gray',  label='Ère Boeing — WWII & Cold War')
ax.axvspan(1970, 1990, alpha=0.08, color='red',   label='Boeing Bust & récession')
ax.axvspan(1990, 2020, alpha=0.08, color='green', label='Révolution Tech')

ax.grid(True, which="both", ls="-", alpha=0.2)
ax.set_title(f'Évolution démographique de {CITY_NAME}\n'
             f'De 302 habitants (1860) à 737 255 habitants (2020)',
             fontsize=16, pad=20, fontweight='bold')
ax.set_xlabel('Année', fontsize=12)
ax.set_ylabel('Population (échelle log)', fontsize=12)
ax.set_xticks(years)
plt.xticks(rotation=45)
ax.set_yticks([1e2, 1e3, 1e4, 1e5, 1e6])
ax.set_yticklabels(['100', '1k', '10k', '100k', '1M'])
ax.legend(fontsize=10, loc='upper left')

for x, y, text, color, xytext in annotations:
    ax.annotate(text, xy=(x, y), xytext=xytext,
                arrowprops=dict(facecolor=color, shrink=0.05, width=1.5),
                bbox=dict(boxstyle="round", alpha=0.1, color=color),
                fontsize=9)

for year, pop in zip(years, population):
    if year in [1860, 1950, 1980, 2020]:
        ax.text(year, pop * 1.5,
                f"{pop:,}".replace(",", " "),
                ha='center', fontsize=10, fontweight='bold',
                bbox=dict(boxstyle="round", alpha=0.2, color=CITY_COLOR))

plt.tight_layout()
plt.savefig('seattle_wa_population.png', dpi=300, bbox_inches='tight')
plt.show()

import matplotlib.pyplot as plt
import numpy as np

CITY_NAME = "Minneapolis, Minnesota"
CITY_COLOR = '#1B4F72'

years = [1850, 1860, 1870, 1880, 1890, 1900, 1910, 1920, 1930, 1940,
         1950, 1960, 1970, 1980, 1990, 2000, 2010, 2020]
population = [200, 2564, 13066, 46887, 164738, 202718, 301408, 380582,
              464356, 492370, 521718, 482872, 434400, 370951,
              368383, 382618, 382578, 429606]

annotations = [
    (1850, 200,    "🌊 Chutes Saint Anthony — moulins", 'brown',  (1851, 80)),
    (1870, 13066,  "🌾 Capitale mondiale farine",       'gold',   (1852, 8000)),
    (1890, 164738, "🚂 Railroad boom",                  'gray',   (1872, 100000)),
    (1910, 301408, "🪓 Bois + farine = empire",         'green',  (1892, 350000)),
    (1950, 521718, "📍 Pic historique",                 'blue',   (1932, 700000)),
    (1980, 370951, "📉 Désindustrialisation",           'red',    (1962, 700000)),
    (2000, 382618, "🌍 Immigrés somaliens & hmong",     'teal',   (1982, 600000)),
    (2020, 429606, "✊ George Floyd — mai 2020",        'black',  (2003, 700000)),
]

fig, ax = plt.subplots(figsize=(15, 9))
plt.style.use('seaborn-v0_8')

ax.semilogy(years, population, marker='o', color=CITY_COLOR,
            linewidth=2.5, markersize=8, markerfacecolor='white',
            markeredgewidth=2, markeredgecolor=CITY_COLOR)

ax.axvspan(1850, 1900, alpha=0.15, color='brown', label='Ère moulins & farine')
ax.axvspan(1900, 1950, alpha=0.08, color='blue',  label='Boom industriel & immigration')
ax.axvspan(1950, 1990, alpha=0.08, color='red',   label='Déclin & white flight')
ax.axvspan(1990, 2020, alpha=0.08, color='green', label='Diversification & renaissance')

ax.grid(True, which="both", ls="-", alpha=0.2)
ax.set_title(f'Évolution démographique de {CITY_NAME}\n'
             f'De 200 habitants (1850) à 429 606 habitants (2020)',
             fontsize=16, pad=20, fontweight='bold')
ax.set_xlabel('Année', fontsize=12)
ax.set_ylabel('Population (échelle log)', fontsize=12)
ax.set_xticks(years)
plt.xticks(rotation=45)
ax.set_yticks([1e2, 1e3, 1e4, 1e5, 1e6])
ax.set_yticklabels(['100', '1k', '10k', '100k', '1M'])
ax.legend(fontsize=10, loc='upper left')

for x, y, text, color, xytext in annotations:
    ax.annotate(text, xy=(x, y), xytext=xytext,
                arrowprops=dict(facecolor=color, shrink=0.05, width=1.5),
                bbox=dict(boxstyle="round", alpha=0.1, color=color),
                fontsize=9)

for year, pop in zip(years, population):
    if year in [1850, 1950, 1980, 2020]:
        ax.text(year, pop * 1.5,
                f"{pop:,}".replace(",", " "),
                ha='center', fontsize=10, fontweight='bold',
                bbox=dict(boxstyle="round", alpha=0.2, color=CITY_COLOR))

plt.tight_layout()
plt.savefig('minneapolis_mn_population.png', dpi=300, bbox_inches='tight')
plt.show()

import matplotlib.pyplot as plt
import numpy as np

CITY_NAME = "Long Beach, California"
CITY_COLOR = '#1A8C6F'

years = [1880, 1890, 1900, 1910, 1920, 1930, 1940, 1950, 1960, 1970,
         1980, 1990, 2000, 2010, 2020]
population = [564, 1887, 2252, 17809, 55593, 142032, 164271, 250767,
              344168, 358633, 361334, 429433, 461522, 462257, 466742]

annotations = [
    (1880, 564,    "🏖️ Station balnéaire fondée",        'brown',  (1881, 200)),
    (1900, 2252,   "🚂 Railroad — tourists arrivent",    'gray',   (1882, 1500)),
    (1910, 17809,  "🛢️ Pétrole découvert nearby",        'black',  (1892, 12000)),
    (1920, 55593,  "⛽ Signal Hill oil boom (1921)",     'orange', (1902, 40000)),
    (1930, 142032, "🌊 Tsunami 1933 — séisme LB",        'blue',   (1912, 200000)),
    (1940, 164271, "⚓ Base navale — WWII",              'navy',   (1922, 280000)),
    (1950, 250767, "✈️ Douglas Aircraft boom",           'purple', (1932, 380000)),
    (1980, 361334, "🚢 Port devient #1 USA",             'teal',   (1962, 480000)),
    (1990, 429433, "🌍 Immigration Cambodge & Mexique",  'green',  (1972, 550000)),
    (2020, 466742, "📦 Amazon — port post-COVID",        'cyan',   (2003, 580000)),
]

fig, ax = plt.subplots(figsize=(15, 9))
plt.style.use('seaborn-v0_8')

ax.semilogy(years, population, marker='o', color=CITY_COLOR,
            linewidth=2.5, markersize=8, markerfacecolor='white',
            markeredgewidth=2, markeredgecolor=CITY_COLOR)

ax.axvspan(1880, 1920, alpha=0.15, color='brown', label='Ère balnéaire & pétrole')
ax.axvspan(1920, 1950, alpha=0.08, color='blue',  label='Oil boom & WWII')
ax.axvspan(1950, 1980, alpha=0.08, color='gray',  label='Industrie aéronautique')
ax.axvspan(1980, 2020, alpha=0.08, color='green', label='Port & diversification')

ax.grid(True, which="both", ls="-", alpha=0.2)
ax.set_title(f'Évolution démographique de {CITY_NAME}\n'
             f'De 564 habitants (1880) à 466 742 habitants (2020)',
             fontsize=16, pad=20, fontweight='bold')
ax.set_xlabel('Année', fontsize=12)
ax.set_ylabel('Population (échelle log)', fontsize=12)
ax.set_xticks(years)
plt.xticks(rotation=45)
ax.set_yticks([1e2, 1e3, 1e4, 1e5, 1e6])
ax.set_yticklabels(['100', '1k', '10k', '100k', '1M'])
ax.legend(fontsize=10, loc='upper left')

for x, y, text, color, xytext in annotations:
    ax.annotate(text, xy=(x, y), xytext=xytext,
                arrowprops=dict(facecolor=color, shrink=0.05, width=1.5),
                bbox=dict(boxstyle="round", alpha=0.1, color=color),
                fontsize=9)

for year, pop in zip(years, population):
    if year in [1880, 1930, 1960, 2020]:
        ax.text(year, pop * 1.5,
                f"{pop:,}".replace(",", " "),
                ha='center', fontsize=10, fontweight='bold',
                bbox=dict(boxstyle="round", alpha=0.2, color=CITY_COLOR))

plt.tight_layout()
plt.savefig('long_beach_ca_population.png', dpi=300, bbox_inches='tight')
plt.show()



import matplotlib.pyplot as plt
import numpy as np

CITY_NAME = "Oakland, California"
CITY_COLOR = '#FFD700'

years = [1860, 1870, 1880, 1890, 1900, 1910, 1920, 1930, 1940, 1950,
         1960, 1970, 1980, 1990, 2000, 2010, 2020]
population = [1543, 10500, 34555, 48682, 66960, 150174, 216261, 284063,
              302163, 384575, 367548, 361561, 339337, 372242,
              399484, 390724, 440646]

annotations = [
    (1860, 1543,   "🚂 Terminal railroad Transcontinental", 'brown', (1861, 600)),
    (1870, 10500,  "⚓ Port Oakland fondé",                'blue',  (1862, 7000)),
    (1920, 216261, "🔥 Réfugiés tremblement SF (1906)",    'red',   (1888, 150000)),
    (1910, 150174, "🏭 Industrie lourde & Kaiser",         'gray',  (1892, 280000)),
    (1940, 302163, "⚓ WWII — Kaiser Shipyards",           'navy',  (1922, 450000)),
    (1950, 384575, "🌍 Grande migration noire du Sud",     'green', (1932, 550000)),
    (1970, 361561, "✊ Black Panthers fondés ici (1966)",  'black', (1948, 600000)),
    (1990, 372242, "🔥 Feux d'Oakland Hills (1991)",      'orange',(1973, 550000)),
    (2000, 399484, "💻 Débordement tech SF Bay",           'teal',  (1982, 580000)),
    (2020, 440646, "🚀 Gentrification accélérée",          'cyan',  (2003, 580000)),
]

fig, ax = plt.subplots(figsize=(15, 9))
plt.style.use('seaborn-v0_8')

ax.semilogy(years, population, marker='o', color=CITY_COLOR,
            linewidth=2.5, markersize=8, markerfacecolor='white',
            markeredgewidth=2, markeredgecolor=CITY_COLOR)

ax.axvspan(1860, 1910, alpha=0.15, color='brown', label='Ère railroad & port')
ax.axvspan(1910, 1950, alpha=0.08, color='blue',  label='Industrie lourde & WWII')
ax.axvspan(1950, 1990, alpha=0.08, color='green', label='Grande migration & Black Power')
ax.axvspan(1990, 2020, alpha=0.08, color='gold',  label='Tech spillover & gentrification')

ax.grid(True, which="both", ls="-", alpha=0.2)
ax.set_title(f'Évolution démographique de {CITY_NAME}\n'
             f'De 1 543 habitants (1860) à 440 646 habitants (2020)',
             fontsize=16, pad=20, fontweight='bold')
ax.set_xlabel('Année', fontsize=12)
ax.set_ylabel('Population (échelle log)', fontsize=12)
ax.set_xticks(years)
plt.xticks(rotation=45)
ax.set_yticks([1e2, 1e3, 1e4, 1e5, 1e6])
ax.set_yticklabels(['100', '1k', '10k', '100k', '1M'])
ax.legend(fontsize=10, loc='upper left')

for x, y, text, color, xytext in annotations:
    ax.annotate(text, xy=(x, y), xytext=xytext,
                arrowprops=dict(facecolor=color, shrink=0.05, width=1.5),
                bbox=dict(boxstyle="round", alpha=0.1, color=color),
                fontsize=9)

for year, pop in zip(years, population):
    if year in [1860, 1910, 1950, 2020]:
        ax.text(year, pop * 1.5,
                f"{pop:,}".replace(",", " "),
                ha='center', fontsize=10, fontweight='bold',
                bbox=dict(boxstyle="round", alpha=0.2, color=CITY_COLOR))

plt.tight_layout()
plt.savefig('oakland_ca_population.png', dpi=300, bbox_inches='tight')
plt.show()


import matplotlib.pyplot as plt
import numpy as np

CITY_NAME = "Portland, Oregon"
CITY_COLOR = '#2E8B57'

years = [1850, 1860, 1870, 1880, 1890, 1900, 1910, 1920, 1930, 1940,
         1950, 1960, 1970, 1980, 1990, 2000, 2010, 2020]
population = [821, 2874, 8293, 17577, 46385, 90426, 207214, 258288,
              301815, 305394, 373628, 372676, 379967, 366383,
              437319, 529121, 583776, 652503]

annotations = [
    (1850, 821,    "🌲 'Stumptown' fondée",              'brown', (1851, 300)),
    (1870, 8293,   "⚓ Port fluvial Willamette",          'blue',  (1852, 5000)),
    (1890, 46385,  "🚂 Railroad transcontinental arrive", 'gray',  (1872, 35000)),
    (1910, 207214, "🌸 Lewis & Clark Exposition (1905)", 'green', (1887, 180000)),
    (1940, 305394, "⚓ Shipyards Kaiser — WWII",         'navy',  (1922, 450000)),
    (1950, 373628, "🌉 Vanport flood 1948 — noirs déplacés",'red',(1932, 550000)),
    (1990, 437319, "🌿 Ville verte & Nike nearby",       'teal',  (1972, 600000)),
    (2000, 529121, "☕ Portland weird culture naît",      'brown', (1982, 650000)),
    (2020, 652503, "🔥 Manifestations BLM + Antifa 2020",'black', (2003, 750000)),
]

fig, ax = plt.subplots(figsize=(15, 9))
plt.style.use('seaborn-v0_8')

ax.semilogy(years, population, marker='o', color=CITY_COLOR,
            linewidth=2.5, markersize=8, markerfacecolor='white',
            markeredgewidth=2, markeredgecolor=CITY_COLOR)

ax.axvspan(1850, 1905, alpha=0.15, color='brown', label='Ère pionnière & port')
ax.axvspan(1905, 1950, alpha=0.08, color='blue',  label='Croissance industrielle')
ax.axvspan(1950, 1990, alpha=0.08, color='red',   label='Stagnation & ségrégation')
ax.axvspan(1990, 2020, alpha=0.08, color='green', label='Renaissance & weird Portland')

ax.grid(True, which="both", ls="-", alpha=0.2)
ax.set_title(f'Évolution démographique de {CITY_NAME}\n'
             f'De 821 habitants (1850) à 652 503 habitants (2020)',
             fontsize=16, pad=20, fontweight='bold')
ax.set_xlabel('Année', fontsize=12)
ax.set_ylabel('Population (échelle log)', fontsize=12)
ax.set_xticks(years)
plt.xticks(rotation=45)
ax.set_yticks([1e2, 1e3, 1e4, 1e5, 1e6])
ax.set_yticklabels(['100', '1k', '10k', '100k', '1M'])
ax.legend(fontsize=10, loc='upper left')

for x, y, text, color, xytext in annotations:
    ax.annotate(text, xy=(x, y), xytext=xytext,
                arrowprops=dict(facecolor=color, shrink=0.05, width=1.5),
                bbox=dict(boxstyle="round", alpha=0.1, color=color),
                fontsize=9)

for year, pop in zip(years, population):
    if year in [1850, 1910, 1950, 2020]:
        ax.text(year, pop * 1.5,
                f"{pop:,}".replace(",", " "),
                ha='center', fontsize=10, fontweight='bold',
                bbox=dict(boxstyle="round", alpha=0.2, color=CITY_COLOR))

plt.tight_layout()
plt.savefig('portland_or_population.png', dpi=300, bbox_inches='tight')
plt.show()


